# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='snake.message',
  syntax='proto3',
  serialized_options=b'\252\002\023Snake.Proto.Message',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\x12\rsnake.message\x1a\x0cshared.proto\"g\n\x0fS2CStartMessage\x12(\n\x08GameInfo\x18\x01 \x01(\x0b\x32\x16.snake.shared.GameInfo\x12*\n\x05World\x18\x02 \x01(\x0b\x32\x1b.snake.shared.WorldSnapshot\"=\n\x0fS2CRoundMessage\x12*\n\x05World\x18\x01 \x01(\x0b\x32\x1b.snake.shared.WorldSnapshot\"\x1e\n\rS2CEndMessage\x12\r\n\x05Score\x18\x01 \x01(\x05\"A\n\x14S2CPlayerListMessage\x12)\n\x07Players\x18\x01 \x03(\x0b\x32\x18.snake.shared.PlayerInfo\"\x91\x01\n\x0e\x43\x32SAuthMessage\x12\r\n\x05Token\x18\x01 \x01(\t\x12\x36\n\x04Type\x18\x02 \x01(\x0e\x32(.snake.message.C2SAuthMessage.ClientType\x12\x12\n\nPlayerName\x18\x03 \x01(\t\"$\n\nClientType\x12\n\n\x06Player\x10\x00\x12\n\n\x06Master\x10\x01\"\x11\n\x0f\x43\x32SStartMessage\"Q\n\x11\x43\x32SCommandMessage\x12\x12\n\nRoundIndex\x18\x01 \x01(\x05\x12(\n\tDirection\x18\x02 \x01(\x0b\x32\x15.snake.shared.Vector2*\x81\x01\n\tMessageId\x12\x0e\n\nS2CInvalid\x10\x00\x12\x0c\n\x08S2CStart\x10\x01\x12\x0c\n\x08S2CRound\x10\x02\x12\n\n\x06S2CEnd\x10\x03\x12\x11\n\rS2CPlayerList\x10\x04\x12\x0b\n\x07\x43\x32SAuth\x10\x05\x12\x0c\n\x08\x43\x32SStart\x10\x06\x12\x0e\n\nC2SCommand\x10\x07\x42\x16\xaa\x02\x13Snake.Proto.Messageb\x06proto3'
  ,
  dependencies=[shared__pb2.DESCRIPTOR,])

_MESSAGEID = _descriptor.EnumDescriptor(
  name='MessageId',
  full_name='snake.message.MessageId',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='S2CInvalid', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='S2CStart', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='S2CRound', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='S2CEnd', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='S2CPlayerList', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='C2SAuth', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='C2SStart', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='C2SCommand', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=564,
  serialized_end=693,
)
_sym_db.RegisterEnumDescriptor(_MESSAGEID)

MessageId = enum_type_wrapper.EnumTypeWrapper(_MESSAGEID)
S2CInvalid = 0
S2CStart = 1
S2CRound = 2
S2CEnd = 3
S2CPlayerList = 4
C2SAuth = 5
C2SStart = 6
C2SCommand = 7


_C2SAUTHMESSAGE_CLIENTTYPE = _descriptor.EnumDescriptor(
  name='ClientType',
  full_name='snake.message.C2SAuthMessage.ClientType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Player', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Master', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=423,
  serialized_end=459,
)
_sym_db.RegisterEnumDescriptor(_C2SAUTHMESSAGE_CLIENTTYPE)


_S2CSTARTMESSAGE = _descriptor.Descriptor(
  name='S2CStartMessage',
  full_name='snake.message.S2CStartMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='GameInfo', full_name='snake.message.S2CStartMessage.GameInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='World', full_name='snake.message.S2CStartMessage.World', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=149,
)


_S2CROUNDMESSAGE = _descriptor.Descriptor(
  name='S2CRoundMessage',
  full_name='snake.message.S2CRoundMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='World', full_name='snake.message.S2CRoundMessage.World', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=212,
)


_S2CENDMESSAGE = _descriptor.Descriptor(
  name='S2CEndMessage',
  full_name='snake.message.S2CEndMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Score', full_name='snake.message.S2CEndMessage.Score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=244,
)


_S2CPLAYERLISTMESSAGE = _descriptor.Descriptor(
  name='S2CPlayerListMessage',
  full_name='snake.message.S2CPlayerListMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Players', full_name='snake.message.S2CPlayerListMessage.Players', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=311,
)


_C2SAUTHMESSAGE = _descriptor.Descriptor(
  name='C2SAuthMessage',
  full_name='snake.message.C2SAuthMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Token', full_name='snake.message.C2SAuthMessage.Token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Type', full_name='snake.message.C2SAuthMessage.Type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PlayerName', full_name='snake.message.C2SAuthMessage.PlayerName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _C2SAUTHMESSAGE_CLIENTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=459,
)


_C2SSTARTMESSAGE = _descriptor.Descriptor(
  name='C2SStartMessage',
  full_name='snake.message.C2SStartMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=478,
)


_C2SCOMMANDMESSAGE = _descriptor.Descriptor(
  name='C2SCommandMessage',
  full_name='snake.message.C2SCommandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='RoundIndex', full_name='snake.message.C2SCommandMessage.RoundIndex', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Direction', full_name='snake.message.C2SCommandMessage.Direction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=561,
)

_S2CSTARTMESSAGE.fields_by_name['GameInfo'].message_type = shared__pb2._GAMEINFO
_S2CSTARTMESSAGE.fields_by_name['World'].message_type = shared__pb2._WORLDSNAPSHOT
_S2CROUNDMESSAGE.fields_by_name['World'].message_type = shared__pb2._WORLDSNAPSHOT
_S2CPLAYERLISTMESSAGE.fields_by_name['Players'].message_type = shared__pb2._PLAYERINFO
_C2SAUTHMESSAGE.fields_by_name['Type'].enum_type = _C2SAUTHMESSAGE_CLIENTTYPE
_C2SAUTHMESSAGE_CLIENTTYPE.containing_type = _C2SAUTHMESSAGE
_C2SCOMMANDMESSAGE.fields_by_name['Direction'].message_type = shared__pb2._VECTOR2
DESCRIPTOR.message_types_by_name['S2CStartMessage'] = _S2CSTARTMESSAGE
DESCRIPTOR.message_types_by_name['S2CRoundMessage'] = _S2CROUNDMESSAGE
DESCRIPTOR.message_types_by_name['S2CEndMessage'] = _S2CENDMESSAGE
DESCRIPTOR.message_types_by_name['S2CPlayerListMessage'] = _S2CPLAYERLISTMESSAGE
DESCRIPTOR.message_types_by_name['C2SAuthMessage'] = _C2SAUTHMESSAGE
DESCRIPTOR.message_types_by_name['C2SStartMessage'] = _C2SSTARTMESSAGE
DESCRIPTOR.message_types_by_name['C2SCommandMessage'] = _C2SCOMMANDMESSAGE
DESCRIPTOR.enum_types_by_name['MessageId'] = _MESSAGEID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

S2CStartMessage = _reflection.GeneratedProtocolMessageType('S2CStartMessage', (_message.Message,), {
  'DESCRIPTOR' : _S2CSTARTMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:snake.message.S2CStartMessage)
  })
_sym_db.RegisterMessage(S2CStartMessage)

S2CRoundMessage = _reflection.GeneratedProtocolMessageType('S2CRoundMessage', (_message.Message,), {
  'DESCRIPTOR' : _S2CROUNDMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:snake.message.S2CRoundMessage)
  })
_sym_db.RegisterMessage(S2CRoundMessage)

S2CEndMessage = _reflection.GeneratedProtocolMessageType('S2CEndMessage', (_message.Message,), {
  'DESCRIPTOR' : _S2CENDMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:snake.message.S2CEndMessage)
  })
_sym_db.RegisterMessage(S2CEndMessage)

S2CPlayerListMessage = _reflection.GeneratedProtocolMessageType('S2CPlayerListMessage', (_message.Message,), {
  'DESCRIPTOR' : _S2CPLAYERLISTMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:snake.message.S2CPlayerListMessage)
  })
_sym_db.RegisterMessage(S2CPlayerListMessage)

C2SAuthMessage = _reflection.GeneratedProtocolMessageType('C2SAuthMessage', (_message.Message,), {
  'DESCRIPTOR' : _C2SAUTHMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:snake.message.C2SAuthMessage)
  })
_sym_db.RegisterMessage(C2SAuthMessage)

C2SStartMessage = _reflection.GeneratedProtocolMessageType('C2SStartMessage', (_message.Message,), {
  'DESCRIPTOR' : _C2SSTARTMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:snake.message.C2SStartMessage)
  })
_sym_db.RegisterMessage(C2SStartMessage)

C2SCommandMessage = _reflection.GeneratedProtocolMessageType('C2SCommandMessage', (_message.Message,), {
  'DESCRIPTOR' : _C2SCOMMANDMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:snake.message.C2SCommandMessage)
  })
_sym_db.RegisterMessage(C2SCommandMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
